//includes top 10 pfp 
//all heavy weight champs >= 1997
const assignImage = (name) => {
    let lowerCaseName = name.toLowerCase();
    

    let formattedName = lowerCaseName.replace(/\s+/g, '-');
    
    return formattedName;
}

const fighters = [
    {name:"Alex Pereira", country:"Brazil", continent:"South America", weightClass:"Light Heavyweight", ufcDebut:"UFC 268", ufcDebutYear:2021 },
    {name:"Alexander Volkanovski", country:"Australia", continent:"Australasia", weightClass:"Featherweight", ufcDebut:"UFC Fight Night 101", ufcDebutYear:2016},
    {name:"Alexandre Pantoja", country:"Brazil", continent:"South America", weightClass:"Flyweight", ufcDebut:"UFC on Fox: Shevchenko vs. Peña", ufcDebutYear:2017},
    {name:"Aljamain Sterling", country:"USA", continent:"North America", weightClass:"Bantamweight", ufcDebut:"UFC 170", ufcDebutYear:2014},
    {name:"Anderson Silva", country:"Brazil", continent:"South America", weightClass:"Middleweight", ufcDebut:"Ultimate Fight Night 5", ufcDebutYear:2006},
    {name:"Andrei Arlovski", country:"Belarus", continent:"Europe", weightClass:"Heavyweight", ufcDebut:"UFC 28", ufcDebutYear:2000},
    {name:"Anthony Pettis", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 136", ufcDebutYear:2011},
    {name:"Benson Henderson", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 129", ufcDebutYear:2011},
    {name:"BJ Penn", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 31", ufcDebutYear:2001},
    {name:"Brandon Moreno", country:"Mexico", continent:"North America", weightClass:"Flyweight", ufcDebut:"UFC Fight Night: Lineker vs. Dodson", ufcDebutYear:2016},
    {name:"Brock Lesnar", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 81", ufcDebutYear:2008},
    {name:"Cain Velasquez", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 83", ufcDebutYear:2008},
    {name:"Carlos Condit", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC Fight Night 18", ufcDebutYear:2009},
    {name:"Charles Oliveira", country:"Brazil", continent:"South America", weightClass:"Lightweight", ufcDebut:"UFC Live: Jones vs. Matyushenko", ufcDebutYear:2010},
    {name:"Chris Weidman", country:"USA", continent:"North America", weightClass:"Middleweight", ufcDebut:"UFC Live: Sanchez vs. Kampmann", ufcDebutYear:2011},
    {name:"Chuck Liddell", country:"USA", continent:"North America", weightClass:"Light Heavyweight", ufcDebut:"UFC 17", ufcDebutYear:1998},
    {name:"Ciryl Gane", country:"France", continent:"Europe", weightClass:"Heavyweight", ufcDebut:"UFC Fight Night: Shevchenko vs. Carmouche 2", ufcDebutYear:2019},
    {name:"Cody Garbrandt", country:"USA", continent:"North America", weightClass:"Bantamweight", ufcDebut:"UFC 182", ufcDebutYear:2015},
    {name:"Colby Covington", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC Fight Night 48", ufcDebutYear:2014},
    {name:"Conor McGregor", country:"Ireland", continent:"Europe", weightClass:"Lightweight", ufcDebut:"UFC on Fuel TV: Mousasi vs. Latifi", ufcDebutYear:2013},
    {name:"Daniel Cormier", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC on Fox 7", ufcDebutYear:2013},
    {name:"Deiveson Figueiredo", country:"Brazil", continent:"South America", weightClass:"Flyweight", ufcDebut:"UFC 212", ufcDebutYear:2017},
    {name:"Demetrious Johnson", country:"USA", continent:"North America", weightClass:"Flyweight", ufcDebut:"UFC 126", ufcDebutYear:2011},
    {name:"Dominick Cruz", country:"USA", continent:"North America", weightClass:"Bantamweight", ufcDebut:"UFC 132", ufcDebutYear:2011},
    {name:"Dricus Du Plessis", country:"South Africa", continent:"Africa", weightClass:"Middleweight", ufcDebut:"UFC Fight Night 179", ufcDebutYear:2020},
    {name:"Dustin Poirier", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 125", ufcDebutYear:2011},
    {name:"Eddie Alvarez", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 178", ufcDebutYear:2014},
    {name:"Fabricio Werdum", country:"Brazil", continent:"South America", weightClass:"Heavyweight", ufcDebut:"UFC 70: Nations Collide", ufcDebutYear:2007},
    {name:"Forrest Griffin", country:"USA", continent:"North America", weightClass:"Light Heavyweight", ufcDebut:"UFC 59", ufcDebutYear:2006},
    {name:"Francis Ngannou", country:"Cameroon", continent:"Africa", weightClass:"Heavyweight", ufcDebut:"UFC on Fox 17", ufcDebutYear:2015},
    {name:"Frank Mir", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 34: High Voltage", ufcDebutYear:2001},
    {name:"Frank Shamrock", country:"USA", continent:"North America", weightClass:"Light Heavyweight", ufcDebut:"UFC Japan", ufcDebutYear:1997},
    {name:"Frankie Edgar", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 67", ufcDebutYear:2007},
    {name:"Georges St-Pierre", country:"Canada", continent:"North America", weightClass:"Middleweight", ufcDebut:"UFC 46", ufcDebutYear:2004},
    {name:"Glover Teixeira", country:"Brazil", continent:"South America", weightClass:"Light Heavyweight", ufcDebut:"UFC 146", ufcDebutYear:2012},
    {name:"Henry Cejudo", country:"USA", continent:"North America", weightClass:"Bantamweight", ufcDebut:"UFC on Fox 13", ufcDebutYear:2014},
    {name:"Ilia Topuria", country:"Spain", continent:"Europe", weightClass:"Featherweight", ufcDebut:"UFC Fight Night: Moraes vs. Sandhagen", ufcDebutYear:2020},
    {name:"Islam Makhachev", country:"Russia", continent:"Asia", weightClass:"Lightweight", ufcDebut:"UFC 187", ufcDebutYear:2015},
    {name:"Israel Adesanya", country:"Nigeria", continent:"Africa", weightClass:"Middleweight", ufcDebut:"UFC 221", ufcDebutYear:2018},
    {name:"Jamahal Hill", country:"USA", continent:"North America", weightClass:"Light Heavyweight", ufcDebut:"UFC Fight Night 166", ufcDebutYear:2020},
    {name:"Jan Blachowicz", country:"Poland", continent:"Europe", weightClass:"Light Heavyweight", ufcDebut:"UFC Fight Night 53", ufcDebutYear:2014},
    {name:"Jiri Prochazka", country:"Czech Republic", continent:"Europe", weightClass:"Light Heavyweight", ufcDebut:"UFC 251", ufcDebutYear:2020},
    {name:"Johny Hendricks", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 101", ufcDebutYear:2009},
    {name:"Jon Jones", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 87", ufcDebutYear:2008},
    {name:"Jose Aldo", country:"Brazil", continent:"South America", weightClass:"Featherweight", ufcDebut:"UFC 123", ufcDebutYear:2010},
    {name:"Junior Dos Santos", country:"Brazil", continent:"South America", weightClass:"Heavyweight", ufcDebut:"UFC 90", ufcDebutYear:2008},
    {name:"Justin Gaethje", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 218", ufcDebutYear:2017},
    {name:"Kamaru Usman", country:"Nigeria", continent:"Africa", weightClass:"Welterweight", ufcDebut:"UFC on Fox 17", ufcDebutYear:2015},
    {name:"Kevin Randleman", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 19", ufcDebutYear:1999},
    {name:"Khabib Nurmagomedov", country:"Russia", continent:"Asia", weightClass:"Lightweight", ufcDebut:"UFC on FX 1", ufcDebutYear:2012},
    {name:"Leon Edwards", country:"England", continent:"Europe", weightClass:"Welterweight", ufcDebut:"UFC Fight Night: Shogun vs. Saint Preux", ufcDebutYear:2014},
    {name:"Luke Rockhold", country:"USA", continent:"North America", weightClass:"Middleweight", ufcDebut:"UFC Fight Night 35", ufcDebutYear:2014},
    {name:"Lyoto Machida", country:"Brazil", continent:"South America", weightClass:"Light Heavyweight", ufcDebut:"UFC 67", ufcDebutYear:2007},
    {name:"Matt Hughes", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 22", ufcDebutYear:1999},
    {name:"Matt Serra", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 31", ufcDebutYear:2001},
    {name:"Mauricio Rua", country:"Brazil", continent:"South America", weightClass:"Light Heavyweight", ufcDebut:"UFC 76", ufcDebutYear:2007},
    {name:"Max Holloway", country:"USA", continent:"North America", weightClass:"Featherweight", ufcDebut:"UFC 143", ufcDebutYear:2012},
    {name:"Michael Bisping", country:"England", continent:"Europe", weightClass:"Middleweight", ufcDebut:"UFC 66", ufcDebutYear:2006},
    {name:"Petr Yan", country:"Russia", continent:"Asia", weightClass:"Bantamweight", ufcDebut:"UFC Fight Night 132", ufcDebutYear:2018},
    {name:"Quinton Jackson", country:"USA", continent:"North America", weightClass:"Light Heavyweight", ufcDebut:"UFC 67", ufcDebutYear:2007},
    {name:"Rafael Dos Anjos", country:"Brazil", continent:"South America", weightClass:"Lightweight", ufcDebut:"UFC 91", ufcDebutYear:2008},
    {name:"Randy Couture", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 13", ufcDebutYear:1997},
    {name:"Rashad Evans", country:"USA", continent:"North America", weightClass:"Light Heavyweight", ufcDebut:"UFC Ultimate Fight Night 4", ufcDebutYear:2006},
    {name:"Renan Barao", country:"Brazil", continent:"South America", weightClass:"Bantamweight", ufcDebut:"UFC 130", ufcDebutYear:2011},
    {name:"Robbie Lawler", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 37", ufcDebutYear:2002},
    {name:"Robert Whittaker", country:"Australia", continent:"Australasia", weightClass:"Middleweight", ufcDebut:"UFC on FX 6", ufcDebutYear:2012},
    {name:"Sean O'Malley", country:"USA", continent:"North America", weightClass:"Bantamweight", ufcDebut:"UFC 222", ufcDebutYear:2018},
    {name:"Sean Strickland", country:"USA", continent:"North America", weightClass:"Middleweight", ufcDebut:"UFC 171", ufcDebutYear:2014},
    {name:"Shane Carwin", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 84", ufcDebutYear:2008},
    {name:"Stipe Miocic", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 136", ufcDebutYear:2011},
    {name:"Tito Ortiz", country:"USA", continent:"North America", weightClass:"Light Heavyweight", ufcDebut:"UFC 13", ufcDebutYear:1997},
    {name:"TJ Dillashaw", country:"USA", continent:"North America", weightClass:"Bantamweight", ufcDebut:"UFC on Fuel TV 1", ufcDebutYear:2012},
    {name:"Tom Aspinall", country:"England", continent:"Europe", weightClass:"Heavyweight", ufcDebut:"UFC on ESPN 14", ufcDebutYear:2020},
    {name:"Tony Ferguson", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 135", ufcDebutYear:2011},
    {name:"Tyron Woodley", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 156", ufcDebutYear:2013},
    {name:"Vitor Belfort", country:"Brazil", continent:"South America", weightClass:"Light Heavyweight", ufcDebut:"UFC 12", ufcDebutYear:1997},
    {name:"Yair Rodriguez", country:"Mexico", continent:"North America", weightClass:"Featherweight", ufcDebut:"UFC 180", ufcDebutYear:2014},

    //{name:"", country:"USA", continent:"North America", weightClass:"Flyweight", ufcDebut:"", ufcDebutYear:},
    //honourable mentions - chael sonnen, diaz bros, yoel romero, overeem, urijah faber, masvidal, demien maia, gustaffson, dan henderson, chandler, chimaev
    //removed fighters
    //{name:"Antonio Rodrigo Nogueira", country:"Brazil", continent:"South America", weightClass:"Heavyweight", ufcDebut:"UFC 73", ufcDebutYear:2007},
    //{name:"Jens Pulver", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 22", ufcDebutYear:1999},
    //    {name:"Sean Sherk", country:"USA", continent:"North America", weightClass:"Lightweight", ufcDebut:"UFC 30", ufcDebutYear:2001},
    //{name:"Pat Miletich", country:"USA", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 16", ufcDebutYear:1998},
    //{name:"Mark Coleman", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 10", ufcDebutYear:1996},
    //{name:"Maurice Smith", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 14", ufcDebutYear:1997},
    //  {name:"Tim Sylvia", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 39", ufcDebutYear:2002},
    //{name:"Bas Rutten", country:"Netherlands", continent:"Europe", weightClass:"Heavyweight", ufcDebut:"UFC 18", ufcDebutYear:1999},
    //{name:"Evan Tanner", country:"USA", continent:"North America", weightClass:"Middleweight", ufcDebut:"UFC 18", ufcDebutYear:1999},
    //{name:"Dave Menne", country:"USA", continent:"North America", weightClass:"Middleweight", ufcDebut:"UFC 24", ufcDebutYear:2000},
    //{name:"Murilo Bustamante", country:"Brazil", continent:"South America", weightClass:"Middleweight", ufcDebut:"UFC 25", ufcDebutYear:2000},
    //    {name:"Rich Franklin", country:"USA", continent:"North America", weightClass:"Middleweight", ufcDebut:"UFC 42", ufcDebutYear:2003},   
    //{name:"Josh Barnett", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 28", ufcDebutYear:2000},
    //{name:"Ricco Rodriguez", country:"USA", continent:"North America", weightClass:"Heavyweight", ufcDebut:"UFC 32", ufcDebutYear:2001},
    //    {name:"Carlos Newton", country:"Canada", continent:"North America", weightClass:"Welterweight", ufcDebut:"UFC 17", ufcDebutYear:1998},
];
export default fighters